# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 17ed8d164e44bf717276f0947cb727b9b9eb1aefeab43af03d8b4eece3c6fcab48911ea0fc1a5feb7638dbd35c59a49b042957c5c453edb82505f73872074c2d

test:
  secret_key_base: 0c002539eaa82976761dd05831000d9ac946432a2e52c6aa8a3e6c5c4498acf7dfb496f8f9bc4e1d18412572de28925507f31666fc5ef0497bbc3a520ef7db56

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
